# Generated by Django 4.1.3 on 2022-11-20 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Введите возвраст пациента')),
                ('gender', models.CharField(choices=[('w', 'Женщина'), ('m', 'Мужчина')], max_length=1, verbose_name='Пол пациента')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VKResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('result_vkr', models.FloatField(blank=True, null=True, verbose_name='Результата VKR')),
                ('wbc', models.FloatField(blank=True, null=True)),
                ('lymf', models.FloatField(blank=True, null=True)),
                ('mon', models.FloatField(blank=True, null=True)),
                ('neu', models.FloatField(blank=True, null=True)),
                ('eos', models.FloatField(blank=True, null=True)),
                ('bas', models.FloatField(blank=True, null=True)),
                ('hgb', models.FloatField(blank=True, null=True)),
                ('plt', models.FloatField(blank=True, null=True)),
                ('cd45_cd3', models.FloatField(blank=True, null=True)),
                ('cd45_cd19', models.FloatField(blank=True, null=True)),
                ('cd45_cd3_cd4', models.FloatField(blank=True, null=True)),
                ('cd3_cd4_cd3_cd8', models.FloatField(blank=True, null=True)),
                ('cd45_cd3_cd16_56', models.FloatField(blank=True, null=True)),
                ('cd45_cd3_cd16bright_cd56dim', models.FloatField(blank=True, null=True)),
                ('circulating_immune_complex', models.FloatField(blank=True, null=True)),
                ('hct_test_spontaneous', models.FloatField(blank=True, null=True)),
                ('hct_test_stimulated', models.FloatField(blank=True, null=True)),
                ('cd3_ifny_stimulated', models.FloatField(blank=True, null=True)),
                ('cd3_ifny_spontaneous', models.FloatField(blank=True, null=True)),
                ('index_cd3_ifny_spontaneous', models.FloatField(blank=True, null=True)),
                ('cd3_tnfa_stimulated', models.FloatField(blank=True, null=True)),
                ('cd3_tnfa_spontaneous', models.FloatField(blank=True, null=True)),
                ('index_cd3_tnfa_stimulated', models.FloatField(blank=True, null=True)),
                ('cd3_il2_stimulated', models.FloatField(blank=True, null=True)),
                ('cd3_il2_spontaneous', models.FloatField(blank=True, null=True)),
                ('index_cd3_il2_stimulated', models.FloatField(blank=True, null=True)),
                ('fno', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_res', to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Снимок МРТ')),
                ('result', models.CharField(max_length=20, verbose_name='Результат распознования')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_pred', to='main.patient', verbose_name='Введите имя пациента')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
